# Generated by Django 5.1.5 on 2025-01-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexus_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="status",
            field=models.CharField(
                choices=[("Not Solved", "Not solved"), ("Solved", "Solved")],
                default="Not Solved",
                max_length=20,
            ),
        ),
    ]
