# Generated by Django 5.1.5 on 2025-01-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexus_app", "0003_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="farmsize",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
