# Generated by Django 5.1.5 on 2025-01-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexus_app", "0005_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
